apiVersion: metrics.newrelic/v1alpha1
kind: ExternalMetric
metadata:
  name: sample-application
  namespace: custom-metrics
spec:
  name: sample-application
  resource:
    resource: "deployment"
  queries:
    - id: sample-application
      query: "SELECT latest(message) FROM testhpa"
