apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
  namespace: custom-metrics
spec:
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
      - name: sample-application
        image: kuperiu/sample_application
